// import AsyncStorage from '@react-native-async-storage/async-storage';
// import * as FileSystem from 'expo-file-system';

// const OFFLINE_QUEUE_KEY = '@jaundicare_offline_queue';
// const OFFLINE_HISTORY_KEY = '@jaundicare_offline_history';

// export interface OfflineQueueItem {
//   id: string;
//   ageHours: number;
//   feedingStatus: 'good' | 'poor';
//   state: string;
//   observedSigns: string[];
//   localImageFilePath: string; // References file:// URI inside the device application sandbox
//   timestamp: number;
// }

// export interface OfflineHistoryRecord extends Omit<OfflineQueueItem, 'localImageFilePath'> {
//   triageLevel: 'RED' | 'AMBER' | 'GREEN';
//   decisionReason: string;
//   confidence: number;
//   localImageFilePath: string;
//   syncStatus: 'PENDING_SYNC';
// }

// // Save image asset locally to device storage and store metadata record details
// export const saveScreeningOffline = async (
//   screeningData: Omit<OfflineQueueItem, 'id' | 'localImageFilePath' | 'timestamp'>,
//   localPrediction: { triageLevel: 'RED' | 'AMBER' | 'GREEN'; decisionReason: string; confidence: number },
//   temporaryImageUri: string // URI generated by camera capture before upload
// ): Promise<string> => {
//   const id = `offline_${Date.now()}`;
//   const filename = `${id}.jpg`;
//   const permanentLocalPath = `${FileSystem.documentDirectory}${filename}`;

//   try {
//     // 1. Copy image out of temporary cache into permanent sandbox directory
//     await FileSystem.copyAsync({
//       from: temporaryImageUri,
//       to: permanentLocalPath
//     });

//     // 2. Build the Sync Queue reference object
//     const queueItem: OfflineQueueItem = {
//       id,
//       ...screeningData,
//       localImageFilePath: permanentLocalPath,
//       timestamp: Date.now()
//     };

//     // 3. Build the UI History placeholder reference object
//     const historyRecord: OfflineHistoryRecord = {
//       ...queueItem,
//       triageLevel: localPrediction.triageLevel,
//       decisionReason: localPrediction.decisionReason,
//       confidence: localPrediction.confidence,
//       syncStatus: 'PENDING_SYNC'
//     };

//     // 4. Save to AsyncStorage arrays
//     const existingQueue = await getOfflineQueue();
//     const existingHistory = await getOfflineHistory();

//     await AsyncStorage.setItem(OFFLINE_QUEUE_KEY, JSON.stringify([...existingQueue, queueItem]));
//     await AsyncStorage.setItem(OFFLINE_HISTORY_KEY, JSON.stringify([...existingHistory, historyRecord]));

//     return id;
//   } catch (error) {
//     console.error('[OfflineStore] Failed to commit records locally:', error);
//     throw error;
//   }
// };

// export const getOfflineQueue = async (): Promise<OfflineQueueItem[]> => {
//   const data = await AsyncStorage.getItem(OFFLINE_QUEUE_KEY);
//   return data ? JSON.parse(data) : [];
// };

// export const getOfflineHistory = async (): Promise<OfflineHistoryRecord[]> => {
//   const data = await AsyncStorage.getItem(OFFLINE_HISTORY_KEY);
//   return data ? JSON.parse(data) : [];
// };

// export const removeSyncedItem = async (id: string, localFilePath: string) => {
//   // Clear persistent text records from arrays
//   const queue = await getOfflineQueue();
//   const history = await getOfflineHistory();

//   await AsyncStorage.setItem(OFFLINE_QUEUE_KEY, JSON.stringify(queue.filter(item => item.id !== id)));
//   await AsyncStorage.setItem(OFFLINE_HISTORY_KEY, JSON.stringify(history.filter(item => item.id !== id)));

//   // Wipe the physical image space out from the phone to free up space
//   try {
//     await FileSystem.deleteAsync(localFilePath, { idempotent: true });
//   } catch (e) {
//     console.warn('[OfflineStore] File cleanup skipped:', e);
//   }
// };



/**
 * JaundiCare — Offline Store & Sync Queue
 * Stores pending screenings locally when network is unavailable.
 * Syncs automatically when connection restores via _layout.tsx NetInfo listener.
 */

// import AsyncStorage from "@react-native-async-storage/async-storage";
// import * as FileSystem from "expo-file-system";
// import { screeningApi, type ScreeningPayload } from "./api";

// const QUEUE_KEY = "jaundicare:offline_queue";

// export interface QueuedScreening {
//   id: string;
//   payload: ScreeningPayload;
//   queuedAt: string;
//   attempts: number;
// }

// // ── Read the queue ────────────────────────────────────────────
// async function getQueue(): Promise<QueuedScreening[]> {
//   try {
//     const raw = await AsyncStorage.getItem(QUEUE_KEY);
//     return raw ? JSON.parse(raw) : [];
//   } catch {
//     return [];
//   }
// }

// // ── Write the queue ───────────────────────────────────────────
// async function saveQueue(queue: QueuedScreening[]): Promise<void> {
//   try {
//     await AsyncStorage.setItem(QUEUE_KEY, JSON.stringify(queue));
//   } catch (err) {
//     console.error("Failed to save offline queue:", err);
//   }
// }

// // ── Add a screening to the queue ─────────────────────────────
// export async function saveScreeningOffline(payload: ScreeningPayload): Promise<string> {
//   const queue = await getQueue();
//   const id = `offline_${Date.now()}`;
  
//   let permanentUri = payload.imageUri;

//   // Move the photo from the temporary cache directory to the permanent app document sandbox
//   if (payload.imageUri && !payload.imageUri.startsWith("http")) {
//     try {
//       const filename = `${id}.jpg`;
//       permanentUri = `${FileSystem.documentDirectory}${filename}`;
      
//       await FileSystem.copyAsync({
//         from: payload.imageUri,
//         to: permanentUri
//       });
//       console.log(`[OfflineStore] Persisted photo to app sandbox: ${permanentUri}`);
//     } catch (fsErr) {
//       console.error("[OfflineStore] Failed to copy temporary image file:", fsErr);
//       // Fallback to the temporary cache URI if persistence fails so we don't drop the record
//       permanentUri = payload.imageUri;
//     }
//   }

//   // Inject the permanent file system path back into the payload
//   const robustPayload: ScreeningPayload = {
//     ...payload,
//     imageUri: permanentUri,
//   };

//   queue.push({
//     id,
//     payload: robustPayload,
//     queuedAt: new Date().toISOString(),
//     attempts: 0,
//   });

//   await saveQueue(queue);
//   console.log(`[OfflineStore] Queued screening ${id}. Total queued: ${queue.length}`);
//   return id;
// }

// // ── Get pending count for UI badge ───────────────────────────
// export async function getPendingCount(): Promise<number> {
//   const queue = await getQueue();
//   return queue.length;
// }

// // ── Sync all queued screenings ────────────────────────────────
// export async function syncOfflineStore(): Promise<void> {
//   const queue = await getQueue();
//   if (queue.length === 0) return;

//   console.log(`[OfflineStore] Syncing ${queue.length} queued screenings...`);

//   const remaining: QueuedScreening[] = [];

//   for (const item of queue) {
//     try {
//       await screeningApi.analyze(item.payload);
//       console.log(`[OfflineStore] Synced ${item.id}`);

//       // Cleanup: Now that it is safely uploaded, wipe the physical sandbox image file to save device storage
//       if (item.payload.imageUri && item.payload.imageUri.startsWith(FileSystem.documentDirectory ?? "")) {
//         try {
//           await FileSystem.deleteAsync(item.payload.imageUri, { idempotent: true });
//           console.log(`[OfflineStore] Cleaned up disk file for ${item.id}`);
//         } catch (cleanupErr) {
//           console.warn(`[OfflineStore] File cleanup skipped for ${item.id}:`, cleanupErr);
//         }
//       }
//     } catch (err) {
//       item.attempts += 1;

//       if (item.attempts >= 5) {
//         console.warn(`[OfflineStore] Dropping ${item.id} after ${item.attempts} failed attempts`);
//         // Cleanup file if dropping the queued item to prevent ghost files bloating storage
//         if (item.payload.imageUri && item.payload.imageUri.startsWith(FileSystem.documentDirectory ?? "")) {
//           try {
//             await FileSystem.deleteAsync(item.payload.imageUri, { idempotent: true });
//           } catch (_) {}
//         }
//       } else {
//         remaining.push(item);
//       }
//     }
//   }

//   await saveQueue(remaining);
//   console.log(`[OfflineStore] Sync complete. ${remaining.length} items still pending.`);
// }

/**
 * JaundiCare — Offline Store & Sync Queue
 * Stores pending screenings locally when network is unavailable.
 * Syncs automatically when connection restores via _layout.tsx NetInfo listener.
 */

// import AsyncStorage from "@react-native-async-storage/async-storage";
// import * as FileSystem from "expo-file-system/legacy";
// import { screeningApi, type ScreeningPayload } from "./api";

// const QUEUE_KEY = "jaundicare:offline_queue";

// export interface QueuedScreening {
//   id: string;
//   payload: ScreeningPayload;
//   queuedAt: string;
//   attempts: number;
//   isDeadLetter?: boolean; // Protects corrupted or repeatedly failing records from disappearing
// }

// // Module-level lock flag to isolate asynchronous execution steps securely
// let isSyncing = false;

// // ── Read the queue ────────────────────────────────────────────
// async function getQueue(): Promise<QueuedScreening[]> {
//   try {
//     const raw = await AsyncStorage.getItem(QUEUE_KEY);
//     return raw ? JSON.parse(raw) : [];
//   } catch {
//     return [];
//   }
// }

// // ── Write the queue ───────────────────────────────────────────
// async function saveQueue(queue: QueuedScreening[]): Promise<void> {
//   try {
//     await AsyncStorage.setItem(QUEUE_KEY, JSON.stringify(queue));
//   } catch (err) {
//     console.error("Failed to save offline queue:", err);
//   }
// }

// // ── Add a screening to the queue ─────────────────────────────
// export async function saveScreeningOffline(payload: ScreeningPayload): Promise<string> {
//   const queue = await getQueue();
//   const id = `offline_${Date.now()}`;
  
//   let permanentUri = payload.imageUri;

//   if (payload.imageUri && !payload.imageUri.startsWith("http")) {
//     try {
//       const filename = `${id}.jpg`;
//       permanentUri = `${FileSystem.documentDirectory}${filename}`;
      
//       await FileSystem.copyAsync({
//         from: payload.imageUri,
//         to: permanentUri
//       });
//       console.log(`[OfflineStore] Persisted photo to app sandbox: ${permanentUri}`);
//     } catch (fsErr) {
//       console.error("[OfflineStore] Failed to copy temporary image file:", fsErr);
//       permanentUri = payload.imageUri;
//     }
//   }

//   const robustPayload: ScreeningPayload = {
//     ...payload,
//     imageUri: permanentUri,
//   };

//   queue.push({
//     id,
//     payload: robustPayload,
//     queuedAt: new Date().toISOString(),
//     attempts: 0,
//   });

//   await saveQueue(queue);
//   console.log(`[OfflineStore] Queued screening ${id}. Total queued: ${queue.length}`);
//   return id;
// }

// // ── Get pending count for UI badge ───────────────────────────
// export async function getPendingCount(): Promise<number> {
//   const queue = await getQueue();
//   // Filter out poisoned elements so badges match executable items
//   return queue.filter(item => !item.isDeadLetter).length;
// }

// // ── Sync all queued screenings ────────────────────────────────
// export async function syncOfflineStore(): Promise<void> {
//   // If a synchronization process is already running, exit immediately to prevent race conditions
//   if (isSyncing) {
//     console.log("[OfflineStore] Sync already in progress, skipping concurrent run.");
//     return;
//   }

//   const queue = await getQueue();
//   if (queue.length === 0) return;

//   isSyncing = true;
//   console.log(`[OfflineStore] Syncing ${queue.length} queued screenings...`);

//   const remaining: QueuedScreening[] = [];

//   for (const item of queue) {
//     // Skip processing if the item has been quarantined
//     if (item.isDeadLetter) {
//       remaining.push(item);
//       continue;
//     }

//     try {
//       await screeningApi.analyze(item.payload);
//       console.log(`[OfflineStore] Synced ${item.id}`);

//       // Cleanup physical image file from storage upon successful upload
//       if (item.payload.imageUri && item.payload.imageUri.startsWith(FileSystem.documentDirectory ?? "")) {
//         try {
//           await FileSystem.deleteAsync(item.payload.imageUri, { idempotent: true });
//           console.log(`[OfflineStore] Cleaned up disk file for ${item.id}`);
//         } catch (cleanupErr) {
//           console.warn(`[OfflineStore] File cleanup skipped for ${item.id}:`, cleanupErr);
//         }
//       }
//     } catch (err) {
//       item.attempts += 1;
//       console.error(`[OfflineStore] Failed sync attempt for ${item.id} (${item.attempts}/5):`, err);

//       if (item.attempts >= 5) {
//         console.error(`[OfflineStore] Quarantining item ${item.id} to prevent data loss.`);
//         // Flag the item as a dead-letter rather than dropping it entirely
//         remaining.push({
//           ...item,
//           isDeadLetter: true
//         });
//       } else {
//         remaining.push(item);
//       }
//     }
//   }

//   try {
//     await saveQueue(remaining);
//     console.log(`[OfflineStore] Sync complete. ${remaining.filter(i => !i.isDeadLetter).length} active items still pending.`);
//   } finally {
//     // Release the concurrency lock regardless of whether saving the queue succeeded or failed
//     isSyncing = false;
//   }
// }




// import AsyncStorage from "@react-native-async-storage/async-storage";
// import { File, Paths } from "expo-file-system";
// import { screeningApi, type ScreeningPayload } from "./api";

// const QUEUE_KEY = "jaundicare:offline_queue";

// export interface QueuedScreening {
//   id: string;
//   payload: ScreeningPayload;
//   queuedAt: string;
//   attempts: number;
//   isDeadLetter?: boolean; // Protects corrupted or repeatedly failing records from disappearing
// }

// // Module-level lock flag to isolate asynchronous execution steps securely
// let isSyncing = false;

// // ── Read the queue ────────────────────────────────────────────
// async function getQueue(): Promise<QueuedScreening[]> {
//   try {
//     const raw = await AsyncStorage.getItem(QUEUE_KEY);
//     return raw ? JSON.parse(raw) : [];
//   } catch {
//     return [];
//   }
// }

// // ── Write the queue ───────────────────────────────────────────
// async function saveQueue(queue: QueuedScreening[]): Promise<void> {
//   try {
//     await AsyncStorage.setItem(QUEUE_KEY, JSON.stringify(queue));
//   } catch (err) {
//     console.error("Failed to save offline queue:", err);
//   }
// }

// // ── Add a screening to the queue ─────────────────────────────
// export async function saveScreeningOffline(payload: ScreeningPayload): Promise<string> {
//   const queue = await getQueue();
//   const id = `offline_${Date.now()}`;
  
//   let permanentUri = payload.imageUri;

//   // Move the photo from the temporary cache directory to the permanent app document sandbox
//   if (payload.imageUri && !payload.imageUri.startsWith("http")) {
//     try {
//       const filename = `${id}.jpg`;
      
//       // Modern Expo SDK 56 File API constructor targets
//       const targetFile = new File(Paths.document, filename);
//       const sourceFile = new File(payload.imageUri);
      
//       // Fixed: In SDK 56, file copying is handled via asynchronous .copy()
//       await sourceFile.copy(targetFile);
//       permanentUri = targetFile.uri;
      
//       console.log(`[OfflineStore] Persisted photo to app sandbox: ${permanentUri}`);
//     } catch (fsErr) {
//       console.error("[OfflineStore] Failed to copy temporary image file:", fsErr);
//       // Fallback to the temporary cache URI if persistence fails so we don't drop the record
//       permanentUri = payload.imageUri;
//     }
//   }

//   // Inject the permanent file system path back into the payload
//   const robustPayload: ScreeningPayload = {
//     ...payload,
//     imageUri: permanentUri,
//   };

//   queue.push({
//     id,
//     payload: robustPayload,
//     queuedAt: new Date().toISOString(),
//     attempts: 0,
//   });

//   await saveQueue(queue);
//   console.log(`[OfflineStore] Queued screening ${id}. Total queued: ${queue.length}`);
//   return id;
// }

// // ── Get pending count for UI badge ───────────────────────────
// export async function getPendingCount(): Promise<number> {
//   const queue = await getQueue();
//   // Filter out poisoned elements so badges match executable items
//   return queue.filter(item => !item.isDeadLetter).length;
// }

// // ── Sync all queued screenings ────────────────────────────────
// export async function syncOfflineStore(): Promise<void> {
//   // If a synchronization process is already running, exit immediately to prevent race conditions
//   if (isSyncing) {
//     console.log("[OfflineStore] Sync already in progress, skipping concurrent run.");
//     return;
//   }

//   const queue = await getQueue();
//   if (queue.length === 0) return;

//   isSyncing = true;
//   console.log(`[OfflineStore] Syncing ${queue.length} queued screenings...`);

//   const remaining: QueuedScreening[] = [];

//   for (const item of queue) {
//     // Skip processing if the item has been quarantined
//     if (item.isDeadLetter) {
//       remaining.push(item);
//       continue;
//     }

//     try {
//       await screeningApi.analyze(item.payload);
//       console.log(`[OfflineStore] Synced ${item.id}`);

//       // Cleanup: Now that it is safely uploaded, wipe the physical sandbox image file to save device storage
//       if (item.payload.imageUri && item.payload.imageUri.startsWith(Paths.document.uri)) {
//         try {
//           const fileToDelete = new File(item.payload.imageUri);
//           // Fixed: In SDK 56, file deletion is handled via .delete()
//           await fileToDelete.delete();
//           console.log(`[OfflineStore] Cleaned up disk file for ${item.id}`);
//         } catch (cleanupErr) {
//           console.warn(`[OfflineStore] File cleanup skipped for ${item.id}:`, cleanupErr);
//         }
//       }
//     } catch (err) {
//       item.attempts += 1;
//       console.error(`[OfflineStore] Failed sync attempt for ${item.id} (${item.attempts}/5):`, err);

//       if (item.attempts >= 5) {
//         console.error(`[OfflineStore] Quarantining item ${item.id} to prevent data loss.`);
//         // Flag the item as a dead-letter rather than dropping it entirely
//         remaining.push({
//           ...item,
//           isDeadLetter: true
//         });
//       } else {
//         remaining.push(item);
//       }
//     }
//   }

//   try {
//     await saveQueue(remaining);
//     console.log(`[OfflineStore] Sync complete. ${remaining.filter(i => !i.isDeadLetter).length} active items still pending.`);
//   } finally {
//     // Release the concurrency lock regardless of whether saving the queue succeeded or failed
//     isSyncing = false;
//   }
// }



// /**
//  * JaundiCare — Offline Store Engine
//  * Handles persistent local queue storage, background sandboxing for image attachments,
//  * and background upload synchronization with error insulation.
//  */

// import AsyncStorage from "@react-native-async-storage/async-storage";
// import { File, Paths } from "expo-file-system";
// import { screeningApi, type ScreeningPayload } from "./api";

// const QUEUE_KEY = "jaundicare:offline_queue";
// const MAX_ATTEMPTS = 5;

// export interface QueuedScreening {
//   id: string;
//   payload: ScreeningPayload;
//   queuedAt: string;
//   attempts: number;
//   isDeadLetter?: boolean;
// }

// // Module-level lock flag to isolate asynchronous execution steps securely
// let isSyncing = false;

// // ── Read the queue ────────────────────────────────────────────
// async function getQueue(): Promise<QueuedScreening[]> {
//   try {
//     const raw = await AsyncStorage.getItem(QUEUE_KEY);
//     return raw ? JSON.parse(raw) : [];
//   } catch (error) {
//     console.error("[OfflineStore] Failed to read queue storage string:", error);
//     return [];
//   }
// }

// // ── Write the queue ───────────────────────────────────────────
// async function saveQueue(queue: QueuedScreening[]): Promise<void> {
//   try {
//     await AsyncStorage.setItem(QUEUE_KEY, JSON.stringify(queue));
//   } catch (err) {
//     console.error("[OfflineStore] Failed to save offline queue structurally:", err);
//   }
// }

// // ── Add a screening to the queue ─────────────────────────────
// export async function saveScreeningOffline(payload: ScreeningPayload): Promise<string> {
//   const queue = await getQueue();
//   const id = `offline_${Date.now()}`;
  
//   let permanentUri = payload.imageUri;

//   // Move the photo from the temporary cache directory to the permanent app document sandbox
//   if (payload.imageUri && !payload.imageUri.startsWith("http")) {
//     try {
//       const filename = `${id}.jpg`;
      
//       // Modern Expo SDK 56 File API constructor targets
//       const targetFile = new File(Paths.document, filename);
//       const sourceFile = new File(payload.imageUri);
      
//       // Execute disk transfer
//       await sourceFile.copy(targetFile);
//       permanentUri = targetFile.uri;
      
//       console.log(`[OfflineStore] Persisted photo to app sandbox: ${permanentUri}`);
//     } catch (fsErr) {
//       console.error("[OfflineStore] Failed to copy temporary image file to sandbox:", fsErr);
//       // Fallback to the temporary cache URI if persistence fails so we don't drop the record
//       permanentUri = payload.imageUri;
//     }
//   }

//   // Inject the permanent file system path back into the payload safely
//   const robustPayload: ScreeningPayload = {
//     ...payload,
//     imageUri: permanentUri,
//   };

//   queue.push({
//     id,
//     payload: robustPayload,
//     queuedAt: new Date().toISOString(),
//     attempts: 0,
//   });

//   await saveQueue(queue);
//   console.log(`[OfflineStore] Queued screening ${id}. Total items in pipeline: ${queue.length}`);
//   return id;
// }

// // ── Get pending count for UI badge ───────────────────────────
// export async function getPendingCount(): Promise<number> {
//   const queue = await getQueue();
//   return queue.filter(item => !item.isDeadLetter).length;
// }

// // ── Sync all queued screenings ────────────────────────────────
// export async function syncOfflineStore(): Promise<void> {
//   // Prevent concurrent execution loops across application layers
//   if (isSyncing) {
//     console.log("[OfflineStore] Sync already in progress, skipping concurrent run.");
//     return;
//   }

//   const queue = await getQueue();
//   // Filter out any entries currently flagged as quarantined dead letters
//   const activeItems = queue.filter(item => !item.isDeadLetter);
  
//   if (activeItems.length === 0) return;

//   isSyncing = true;
//   console.log(`[OfflineStore] Syncing ${activeItems.length} active queued screenings...`);

//   // Build a trackable map to match runtime updates efficiently
//   const updatedQueueMap = new Map<string, QueuedScreening>(queue.map(item => [item.id, item]));

//   // Fix Head-of-Line Blocking by processing the transactions in parallel tasks
//   // Using Promise.allSettled avoids catastrophic total failure if one item crashes out
//   await Promise.allSettled(
//     activeItems.map(async (item) => {
//       try {
//         // Execute network analysis request
//         await screeningApi.analyze(item.payload);
//         console.log(`[OfflineStore] Successfully synced tracking item ${item.id}`);

//         // Cleanup: Purge sandboxed binary images to avoid disk bloat
//         if (item.payload.imageUri && item.payload.imageUri.includes("DocumentPicker") || item.payload.imageUri.includes("Documents/")) {
//           try {
//             const fileToDelete = new File(item.payload.imageUri);
//             await fileToDelete.delete();
//             console.log(`[OfflineStore] Cleaned up physical disk file for tracking object: ${item.id}`);
//           } catch (cleanupErr) {
//             console.warn(`[OfflineStore] File physical disk cleanup skipped for item ${item.id}:`, cleanupErr);
//           }
//         }

//         // Drop the fully verified element out of the tracking record map
//         updatedQueueMap.delete(item.id);
//       } catch (err) {
//         const currentRecord = updatedQueueMap.get(item.id);
//         if (currentRecord) {
//           currentRecord.attempts += 1;
//           console.error(`[OfflineStore] Failed sync attempt for ${item.id} (${currentRecord.attempts}/${MAX_ATTEMPTS}):`, err);

//           if (currentRecord.attempts >= MAX_ATTEMPTS) {
//             console.error(`[OfflineStore] Quarantining item ${item.id} permanently to prevent data loss loops.`);
//             currentRecord.isDeadLetter = true;
//           }
//         }
//       }
//     })
//   );

//   try {
//     // Commit remaining items safely back to storage
//     const remainingQueue = Array.from(updatedQueueMap.values());
//     await saveQueue(remainingQueue);
//     console.log(`[OfflineStore] Sync batch routine completed. ${remainingQueue.filter(i => !i.isDeadLetter).length} items remaining active.`);
//   } finally {
//     isSyncing = false;
//   }
// }



// /**
//  * JaundiCare — useOfflineSync Hook (Production-Hardened)
//  * Listens for active cellular network transitions and cleanly routes execution 
//  * to the core transactional storage engine.
//  */

// import { useEffect, useCallback, useRef } from 'react';
// import NetInfo from '@react-native-community/netinfo';

// export async function getPendingCount(): Promise<number> { ... }
// export async function syncOfflineStore(): Promise<void> { ... }

// export const useOfflineSync = () => {
//   const isProcessing = useRef(false);

//   const attemptQueueFlush = useCallback(async () => {
//     // Structural guard preventing concurrent UI loop execution states
//     if (isProcessing.current) return;
    
//     try {
//       // Short-circuit execution if there are zero active items waiting to sync
//       const pendingCount = await getPendingCount();
//       if (pendingCount === 0) return;

//       isProcessing.current = true;
//       console.log(`[useOfflineSync] Network online. Flushing outbox pipeline...`);
      
//       // Delegate all binary file handling, parallel calls, and retries to the core store
//       await syncOfflineStore();
//     } catch (err) {
//       console.error("[useOfflineSync] Background queue synchronization failed:", err);
//     } finally {
//       isProcessing.current = false;
//     }
//   }, []);

//   useEffect(() => {
//     // Subscribes cleanly to local cellular/Wi-Fi connection states
//     const unsubscribe = NetInfo.addEventListener(state => {
//       if (state.isConnected && state.isInternetReachable) {
//         attemptQueueFlush();
//       }
//     });

//     return () => unsubscribe();
//   }, [attemptQueueFlush]);

//   return { forceSync: attemptQueueFlush };
// };


/**
 * JaundiCare — Offline Store Engine
 * Handles persistent local queue storage, background sandboxing for image attachments,
 * and background upload synchronization with error insulation.
 */

import AsyncStorage from "@react-native-async-storage/async-storage";
import { File, Paths } from "expo-file-system";
import { screeningApi, type ScreeningPayload } from "./api";

const QUEUE_KEY = "jaundicare:offline_queue";
const MAX_ATTEMPTS = 5;

export interface QueuedScreening {
  id: string;
  payload: ScreeningPayload;
  queuedAt: string;
  attempts: number;
  isDeadLetter?: boolean;
}

// Module-level lock flag to isolate asynchronous execution steps securely
let isSyncing = false;

// ── Read the queue ────────────────────────────────────────────
async function getQueue(): Promise<QueuedScreening[]> {
  try {
    const raw = await AsyncStorage.getItem(QUEUE_KEY);
    return raw ? JSON.parse(raw) : [];
  } catch (error) {
    console.error("[OfflineStore] Failed to read queue storage string:", error);
    return [];
  }
}

// ── Write the queue ───────────────────────────────────────────
async function saveQueue(queue: QueuedScreening[]): Promise<void> {
  try {
    await AsyncStorage.setItem(QUEUE_KEY, JSON.stringify(queue));
  } catch (err) {
    console.error("[OfflineStore] Failed to save offline queue structurally:", err);
  }
}

// ── Add a screening to the queue ─────────────────────────────
export async function saveScreeningOffline(payload: ScreeningPayload): Promise<string> {
  const queue = await getQueue();
  const id = `offline_${Date.now()}`;
  
  let permanentUri = payload.imageUri;

  // Move the photo from the temporary cache directory to the permanent app document sandbox
  if (payload.imageUri && !payload.imageUri.startsWith("http")) {
    try {
      const filename = `${id}.jpg`;
      
      // Modern Expo SDK File API constructor targets
      const targetFile = new File(Paths.document, filename);
      const sourceFile = new File(payload.imageUri);
      
      // Execute disk transfer
      await sourceFile.copy(targetFile);
      permanentUri = targetFile.uri;
      
      console.log(`[OfflineStore] Persisted photo to app sandbox: ${permanentUri}`);
    } catch (fsErr) {
      console.error("[OfflineStore] Failed to copy temporary image file to sandbox:", fsErr);
      permanentUri = payload.imageUri;
    }
  }

  // Inject the permanent file system path back into the payload safely
  const robustPayload: ScreeningPayload = {
    ...payload,
    imageUri: permanentUri,
  };

  queue.push({
    id,
    payload: robustPayload,
    queuedAt: new Date().toISOString(),
    attempts: 0,
  });

  await saveQueue(queue);
  console.log(`[OfflineStore] Queued screening ${id}. Total items in pipeline: ${queue.length}`);
  return id;
}

// ── Get pending count for UI badge ───────────────────────────
export async function getPendingCount(): Promise<number> {
  const queue = await getQueue();
  return queue.filter(item => !item.isDeadLetter).length;
}

// ── Sync all queued screenings ────────────────────────────────
export async function syncOfflineStore(): Promise<void> {
  // Prevent concurrent execution loops across application layers
  if (isSyncing) {
    console.log("[OfflineStore] Sync already in progress, skipping concurrent run.");
    return;
  }

  const queue = await getQueue();
  const activeItems = queue.filter(item => !item.isDeadLetter);
  
  if (activeItems.length === 0) return;

  isSyncing = true;
  console.log(`[OfflineStore] Syncing ${activeItems.length} active queued screenings...`);

  // Build a trackable map to match runtime updates efficiently
  const updatedQueueMap = new Map<string, QueuedScreening>(queue.map(item => [item.id, item]));

  // Fix Head-of-Line Blocking by processing the transactions in parallel tasks
  await Promise.allSettled(
    activeItems.map(async (item) => {
      try {
        // Execute network analysis request
        await screeningApi.analyze(item.payload);
        console.log(`[OfflineStore] Successfully synced tracking item ${item.id}`);

        // Cleanup: Purge sandboxed binary images to avoid disk bloat
        if (item.payload.imageUri && (item.payload.imageUri.includes("DocumentPicker") || item.payload.imageUri.includes("Documents/"))) {
          try {
            const fileToDelete = new File(item.payload.imageUri);
            await fileToDelete.delete();
            console.log(`[OfflineStore] Cleaned up physical disk file for tracking object: ${item.id}`);
          } catch (cleanupErr) {
            console.warn(`[OfflineStore] File physical disk cleanup skipped for item ${item.id}:`, cleanupErr);
          }
        }

        // Drop the fully verified element out of the tracking record map
        updatedQueueMap.delete(item.id);
      } catch (err) {
        const currentRecord = updatedQueueMap.get(item.id);
        if (currentRecord) {
          currentRecord.attempts += 1;
          console.error(`[OfflineStore] Failed sync attempt for ${item.id} (${currentRecord.attempts}/${MAX_ATTEMPTS}):`, err);

          if (currentRecord.attempts >= MAX_ATTEMPTS) {
            console.error(`[OfflineStore] Quarantining item ${item.id} permanently to prevent data loss loops.`);
            currentRecord.isDeadLetter = true;
          }
        }
      }
    })
  );

  try {
    // Commit remaining items safely back to storage
    const remainingQueue = Array.from(updatedQueueMap.values());
    await saveQueue(remainingQueue);
    console.log(`[OfflineStore] Sync batch routine completed. ${remainingQueue.filter(i => !i.isDeadLetter).length} items remaining active.`);
  } catch (saveErr) {
    console.error("[OfflineStore] Failed to commit updated queue layout status:", saveErr);
  } finally {
    isSyncing = false;
  }
}