import React, { useState } from "react";
import {
  View, Text, TouchableOpacity, ScrollView,
  StyleSheet, Share,
} from "react-native";
import { Ionicons } from "@expo/vector-icons";
import { Colors, Fonts, Radius, Shadow } from "../constants/colors";
import { FacilityCard } from "./FacilityCard";
import { decisionConfig } from "../constants/decisionMap";
import type { ScreeningResult } from "../services/api";

interface Props {
  result: ScreeningResult;
  babyName?: string;
  gestationalAgeWeeks?: number;
}

function getNextSteps(decision: string): string[] {
  switch (decision) {
    case "URGENT_HOSPITAL_REVIEW":
      return [
        "Go to the nearest hospital now — do not wait.",
        "Call ahead if possible so they can prepare.",
        "Take this screening result with you to show the doctor.",
      ];
    case "SAME_DAY_CLINIC_REVIEW":
      return [
        "Visit a clinic or health worker today.",
        "Do not wait until tomorrow.",
        "Continue feeding your baby regularly while travelling.",
      ];
    case "RECHECK_SOON_OR_CLINIC_IF_CONCERNED":
      return [
        "Recheck your baby in a few hours.",
        "Watch for yellowing in the eyes, gums, palms, or soles.",
        "Seek same-day care if anything worsens.",
      ];
    default:
      return [
        "Continue feeding your baby regularly — 8 to 12 times per day.",
        "Check eyes, gums, and palms daily for yellowing.",
        "Run a new screening if any warning signs appear.",
      ];
  }
}

function titleCase(str: string) {
  return str.split("_").map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(" ");
}

export function ResultCard({ result, babyName, gestationalAgeWeeks }: Props) {
  const [mode, setMode] = useState<"parent" | "hw">("parent");
  const dm = decisionConfig(result.final_decision);

  // Gestational age warning
  let gestNote: string | null = null;
  if (gestationalAgeWeeks != null) {
    if (gestationalAgeWeeks < 35) {
      gestNote = `Your baby was born at ${gestationalAgeWeeks} weeks — preterm babies have a lower threshold for jaundice treatment and need closer monitoring.`;
    } else if (gestationalAgeWeeks < 38) {
      gestNote = `Your baby was born at ${gestationalAgeWeeks} weeks (late preterm). Close monitoring is especially important in the first week.`;
    }
  }

  // Confidence display
  const raw = result.image_confidence;
  const confidencePct = raw != null
    ? (raw > 1 ? raw.toFixed(1) : (raw * 100).toFixed(1))
    : "N/A";

  const onShare = async () => {
    const ageHours = result.baby_age_hours;
    const ageDays  = ageHours != null ? Math.floor(ageHours / 24) : null;
    const ageStr   = ageDays != null
      ? ageDays > 0 ? `${ageDays} day(s) and ${ageHours! % 24} hour(s)` : `${ageHours} hours`
      : "Unknown age";

    const summary = `
JaundiCare Screening Summary
─────────────────────────────
Baby: ${babyName ?? "Baby"}
Age at screening: ${ageStr}
Date: ${new Date(result.created_at).toLocaleString()}

RESULT: ${dm.label}

Image analysis: ${titleCase(result.image_prediction ?? "N/A")} (${confidencePct}% confidence)
Triage: ${result.raw_triage_level}
Reason: ${result.final_decision_reason}

NEXT STEPS:
${getNextSteps(result.final_decision).map((s, i) => `${i + 1}. ${s}`).join("\n")}

─────────────────────────────
This is a screening support tool only.
It does not replace a doctor, midwife, or bilirubin test.
Generated by JaundiCare
    `.trim();

    await Share.share({ message: summary, title: `JaundiCare — ${babyName ?? "Baby"} screening result` });
  };

  return (
    <View style={s.container}>
      {/* Mode toggle */}
      <View style={s.modeToggle}>
        <TouchableOpacity
          style={[s.modeBtn, mode === "parent" && s.modeBtnActive]}
          onPress={() => setMode("parent")}
        >
          <Text style={[s.modeBtnText, mode === "parent" && s.modeBtnTextActive]}>Parent View</Text>
        </TouchableOpacity>
        <TouchableOpacity
          style={[s.modeBtn, mode === "hw" && s.modeBtnActive]}
          onPress={() => setMode("hw")}
        >
          <Text style={[s.modeBtnText, mode === "hw" && s.modeBtnTextActive]}>Health Worker</Text>
        </TouchableOpacity>
      </View>

      {/* Trust banner */}
      <View style={s.trustBanner}>
        <Ionicons name="shield-checkmark-outline" size={14} color={Colors.brownLight} />
        <Text style={s.trustText}>
          This is a screening support tool. It does not replace a doctor, midwife, or bilirubin test.
        </Text>
      </View>

      {mode === "parent" ? (
        <>
          {/* Status block */}
          <View style={[s.statusBlock, { borderColor: dm.color, backgroundColor: dm.color + "12" }]}>
            <Text style={s.statusIcon}>{dm.icon}</Text>
            <View style={[s.statusPill, { backgroundColor: dm.color }]}>
              <Text style={s.statusPillText}>{dm.label}</Text>
            </View>
            <Text style={s.parentMessage}>{result.parent_message}</Text>

            {/* Gestational note */}
            {gestNote && (
              <View style={s.gestNote}>
                <Ionicons name="information-circle-outline" size={13} color={Colors.amberDark} />
                <Text style={s.gestNoteText}>{gestNote}</Text>
              </View>
            )}
          </View>

          {/* Next steps */}
          <View style={s.section}>
            <Text style={s.sectionTitle}>What to do next</Text>
            {getNextSteps(result.final_decision).map((step, i) => (
              <View key={i} style={s.stepRow}>
                <View style={[s.stepNum, { backgroundColor: dm.color }]}>
                  <Text style={s.stepNumText}>{i + 1}</Text>
                </View>
                <Text style={s.stepText}>{step}</Text>
              </View>
            ))}
          </View>

          {/* Facilities */}
          {result.recommended_facilities?.length > 0 && (
            <View style={s.section}>
              <Text style={s.sectionTitle}>Nearby facilities</Text>
              {result.recommended_facilities.slice(0, 5).map((f) => (
                <FacilityCard key={f.id} facility={f} />
              ))}
            </View>
          )}

          {/* Notes */}
          {result.notes?.length > 0 && (
            <View style={s.section}>
              <Text style={s.sectionTitle}>Additional notes</Text>
              {result.notes.map((note, i) => (
                <View key={i} style={s.noteRow}>
                  <View style={s.noteDot} />
                  <Text style={s.noteText}>{note}</Text>
                </View>
              ))}
            </View>
          )}

          {/* Share */}
          <TouchableOpacity style={s.shareBtn} onPress={onShare}>
            <Ionicons name="share-outline" size={16} color={Colors.coral} />
            <Text style={s.shareBtnText}>Share screening summary</Text>
          </TouchableOpacity>
        </>
      ) : (
        <>
          {/* Health worker view */}
          <View style={[s.hwBanner, { borderLeftColor: dm.color }]}>
            <Text style={s.hwLabel}>Final Decision</Text>
            <Text style={[s.hwDecision, { color: dm.color }]}>{result.final_decision}</Text>
          </View>

          {[
            ["Image Prediction",    titleCase(result.image_prediction ?? "N/A")],
            ["Confidence",          `${confidencePct}%`],
            ["Confidence Band",     result.confidence_band ?? "N/A"],
            ["Baby Age",            result.baby_age_hours != null ? `${result.baby_age_hours} hours` : "N/A"],
            ["Raw Triage Level",    result.raw_triage_level],
            ["Raw Triage Reason",   result.raw_triage_reason],
            ["Decision Reason",     result.final_decision_reason],
          ].map(([label, value]) => (
            <View key={label} style={s.hwRow}>
              <Text style={s.hwRowLabel}>{label}</Text>
              <Text style={s.hwRowValue}>{value}</Text>
            </View>
          ))}

          {result.recommended_facilities?.length > 0 && (
            <View style={s.section}>
              <Text style={s.sectionTitle}>Recommended Facilities</Text>
              {result.recommended_facilities.slice(0, 5).map((f) => (
                <FacilityCard key={f.id} facility={f} />
              ))}
            </View>
          )}
        </>
      )}
    </View>
  );
}

const s = StyleSheet.create({
  container: { paddingBottom: 20 },

  modeToggle: {
    flexDirection: "row",
    backgroundColor: Colors.cream,
    borderRadius: Radius.lg,
    padding: 4,
    marginBottom: 12,
  },
  modeBtn: {
    flex: 1,
    paddingVertical: 8,
    alignItems: "center",
    borderRadius: Radius.md,
  },
  modeBtnActive:     { backgroundColor: Colors.earth },
  modeBtnText:       { fontFamily: Fonts.medium, fontSize: 13, color: Colors.brownLight },
  modeBtnTextActive: { color: "#fff" },

  trustBanner: {
    flexDirection: "row",
    gap: 6,
    backgroundColor: Colors.amberPale,
    borderRadius: Radius.md,
    padding: 10,
    marginBottom: 12,
    alignItems: "flex-start",
  },
  trustText: { fontFamily: Fonts.regular, fontSize: 12, color: Colors.brownLight, flex: 1, lineHeight: 18 },

  statusBlock: {
    borderWidth: 1.5,
    borderRadius: Radius.lg,
    padding: 16,
    alignItems: "center",
    marginBottom: 16,
  },
  statusIcon:     { fontSize: 32, marginBottom: 8 },
  statusPill:     { paddingHorizontal: 12, paddingVertical: 4, borderRadius: Radius.full, marginBottom: 10 },
  statusPillText: { fontFamily: Fonts.semibold, fontSize: 13, color: "#fff" },
  parentMessage:  { fontFamily: Fonts.medium, fontSize: 14, color: Colors.earth, textAlign: "center", lineHeight: 22 },

  gestNote: {
    flexDirection: "row",
    gap: 6,
    marginTop: 10,
    backgroundColor: Colors.amberPale,
    borderRadius: Radius.md,
    padding: 8,
    alignItems: "flex-start",
  },
  gestNoteText: { fontFamily: Fonts.regular, fontSize: 12, color: Colors.amberDark, flex: 1, lineHeight: 18 },

  section:      { marginBottom: 16 },
  sectionTitle: { fontFamily: Fonts.semibold, fontSize: 14, color: Colors.earth, marginBottom: 10 },

  stepRow: { flexDirection: "row", gap: 10, marginBottom: 8, alignItems: "flex-start" },
  stepNum: { width: 22, height: 22, borderRadius: 11, alignItems: "center", justifyContent: "center" },
  stepNumText: { fontFamily: Fonts.bold, fontSize: 11, color: "#fff" },
  stepText: { fontFamily: Fonts.regular, fontSize: 13, color: Colors.brown, flex: 1, lineHeight: 20 },

  noteRow: { flexDirection: "row", gap: 8, marginBottom: 6, alignItems: "flex-start" },
  noteDot: { width: 5, height: 5, borderRadius: 3, backgroundColor: Colors.amber, marginTop: 7 },
  noteText: { fontFamily: Fonts.regular, fontSize: 13, color: Colors.brown, flex: 1, lineHeight: 20 },

  shareBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    borderWidth: 1.5,
    borderColor: Colors.coral,
    borderRadius: Radius.lg,
    padding: 12,
    marginTop: 8,
  },
  shareBtnText: { fontFamily: Fonts.semibold, fontSize: 13, color: Colors.coral },

  hwBanner: {
    borderLeftWidth: 4,
    paddingLeft: 12,
    paddingVertical: 8,
    marginBottom: 14,
  },
  hwLabel:    { fontFamily: Fonts.medium, fontSize: 11, color: Colors.brownLight, marginBottom: 2 },
  hwDecision: { fontFamily: Fonts.bold, fontSize: 15 },
  hwRow: {
    backgroundColor: Colors.cream,
    borderRadius: Radius.md,
    padding: 10,
    marginBottom: 6,
  },
  hwRowLabel: { fontFamily: Fonts.medium, fontSize: 11, color: Colors.brownLight, marginBottom: 2 },
  hwRowValue: { fontFamily: Fonts.semibold, fontSize: 13, color: Colors.earth },
});