// /**
//  * JaundiCare — ResultCard component
//  * Shows parent view by default.
//  * Health worker technical details only shown if role is health_worker.
//  */

// import React from "react";
// import {
//   View, Text, TouchableOpacity,
//   StyleSheet, Share,
// } from "react-native";
// import { Ionicons } from "@expo/vector-icons";
// import { Colors, Fonts, Radius, Shadow } from "../constants/colors";
// import { FacilityCard } from "./FacilityCard";
// import { decisionConfig } from "../constants/decisionMap";
// import { useAppStore } from "../store/appStore";
// import type { ScreeningResult } from "../services/api";

// interface Props {
//   result: ScreeningResult;
//   babyName?: string;
//   gestationalAgeWeeks?: number;
// }

// function getNextSteps(decision: string): string[] {
//   switch (decision) {
//     case "URGENT_HOSPITAL_REVIEW":
//       return [
//         "Go to the nearest hospital now — do not wait.",
//         "Call ahead if possible so they can prepare.",
//         "Take this screening result with you to show the doctor.",
//       ];
//     case "SAME_DAY_CLINIC_REVIEW":
//       return [
//         "Visit a clinic or health worker today.",
//         "Do not wait until tomorrow.",
//         "Continue feeding your baby regularly while travelling.",
//       ];
//     case "RECHECK_SOON_OR_CLINIC_IF_CONCERNED":
//       return [
//         "Recheck your baby in a few hours.",
//         "Watch for yellowing in the eyes, gums, palms, or soles.",
//         "Seek same-day care if anything worsens.",
//       ];
//     default:
//       return [
//         "Continue feeding your baby regularly — 8 to 12 times per day.",
//         "Check eyes, gums, and palms daily for yellowing.",
//         "Run a new screening if any warning signs appear.",
//       ];
//   }
// }

// function titleCase(str: string) {
//   return str.split("_").map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(" ");
// }

// export function ResultCard({ result, babyName, gestationalAgeWeeks }: Props) {
//   const role = useAppStore((s) => s.role);
//   const isHW = role === "health_worker";
//   const dm   = decisionConfig(result.final_decision);

//   // Gestational age warning
//   let gestNote: string | null = null;
//   if (gestationalAgeWeeks != null) {
//     if (gestationalAgeWeeks < 35) {
//       gestNote = `Your baby was born at ${gestationalAgeWeeks} weeks — preterm babies have a lower threshold for jaundice treatment and need closer monitoring.`;
//     } else if (gestationalAgeWeeks < 38) {
//       gestNote = `Your baby was born at ${gestationalAgeWeeks} weeks (late preterm). Close monitoring is especially important in the first week.`;
//     }
//   }

//   // Confidence display
//   const raw = result.image_confidence;
//   const confidencePct = raw != null
//     ? (raw > 1 ? raw.toFixed(1) : (raw * 100).toFixed(1))
//     : "N/A";

//   const onShare = async () => {
//     const ageHours = result.baby_age_hours;
//     const ageDays  = ageHours != null ? Math.floor(ageHours / 24) : null;
//     const ageStr   = ageDays != null
//       ? ageDays > 0 ? `${ageDays} day(s) and ${ageHours! % 24} hour(s)` : `${ageHours} hours`
//       : "Unknown age";

//     const summary = `
// JaundiCare Screening Summary
// ─────────────────────────────
// Baby: ${babyName ?? "Baby"}
// Age at screening: ${ageStr}
// Date: ${new Date(result.created_at).toLocaleString()}

// RESULT: ${dm.label}

// Image analysis: ${titleCase(result.image_prediction ?? "N/A")} (${confidencePct}% confidence)
// Triage: ${result.raw_triage_level}
// Reason: ${result.final_decision_reason}

// NEXT STEPS:
// ${getNextSteps(result.final_decision).map((s, i) => `${i + 1}. ${s}`).join("\n")}

// ─────────────────────────────
// This is a screening support tool only.
// It does not replace a doctor, midwife, or bilirubin test.
// Generated by JaundiCare
//     `.trim();

//     await Share.share({ message: summary, title: `JaundiCare — ${babyName ?? "Baby"} screening result` });
//   };

//   return (
//     <View style={s.container}>
//       {/* Trust banner */}
//       <View style={s.trustBanner}>
//         <Ionicons name="shield-checkmark-outline" size={14} color={Colors.brownLight} />
//         <Text style={s.trustText}>
//           This is a screening support tool. It does not replace a doctor, midwife, or bilirubin test.
//         </Text>
//       </View>

//       {!isHW ? (
//         <>
//           {/* Status block */}
//           <View style={[s.statusBlock, { borderColor: dm.color, backgroundColor: dm.color + "12" }]}>
//             <Text style={s.statusIcon}>{dm.icon}</Text>
//             <View style={[s.statusPill, { backgroundColor: dm.color }]}>
//               <Text style={s.statusPillText}>{dm.label}</Text>
//             </View>
//             <Text style={s.parentMessage}>{result.parent_message}</Text>

//             {/* Gestational note */}
//             {gestNote && (
//               <View style={s.gestNote}>
//                 <Ionicons name="information-circle-outline" size={13} color={Colors.amberDark} />
//                 <Text style={s.gestNoteText}>{gestNote}</Text>
//               </View>
//             )}
//           </View>

//           {/* Next steps */}
//           <View style={s.section}>
//             <Text style={s.sectionTitle}>What to do next</Text>
//             {getNextSteps(result.final_decision).map((step, i) => (
//               <View key={i} style={s.stepRow}>
//                 <View style={[s.stepNum, { backgroundColor: dm.color }]}>
//                   <Text style={s.stepNumText}>{i + 1}</Text>
//                 </View>
//                 <Text style={s.stepText}>{step}</Text>
//               </View>
//             ))}
//           </View>

//           {/* Facilities */}
//           {result.recommended_facilities?.length > 0 && (
//             <View style={s.section}>
//               <Text style={s.sectionTitle}>Nearby facilities</Text>
//               {result.recommended_facilities.slice(0, 5).map((f) => (
//                 <FacilityCard key={f.id} facility={f} />
//               ))}
//             </View>
//           )}

//           {/* Notes */}
//           {result.notes?.length > 0 && (
//             <View style={s.section}>
//               <Text style={s.sectionTitle}>Additional notes</Text>
//               {result.notes.map((note, i) => (
//                 <View key={i} style={s.noteRow}>
//                   <View style={s.noteDot} />
//                   <Text style={s.noteText}>{note}</Text>
//                 </View>
//               ))}
//             </View>
//           )}

//           {/* Share */}
//           <TouchableOpacity style={s.shareBtn} onPress={onShare}>
//             <Ionicons name="share-outline" size={16} color={Colors.coral} />
//             <Text style={s.shareBtnText}>Share screening summary</Text>
//           </TouchableOpacity>
//         </>
//       ) : (
//         <>
//           {/* Health worker view */}
//           <View style={[s.hwBanner, { borderLeftColor: dm.color }]}>
//             <Text style={s.hwLabel}>Final Decision</Text>
//             <Text style={[s.hwDecision, { color: dm.color }]}>{result.final_decision}</Text>
//           </View>

//           {[
//             ["Image Prediction",    titleCase(result.image_prediction ?? "N/A")],
//             ["Confidence",          `${confidencePct}%`],
//             ["Confidence Band",     result.confidence_band ?? "N/A"],
//             ["Baby Age",            result.baby_age_hours != null ? `${result.baby_age_hours} hours` : "N/A"],
//             ["Raw Triage Level",    result.raw_triage_level],
//             ["Raw Triage Reason",   result.raw_triage_reason],
//             ["Decision Reason",     result.final_decision_reason],
//           ].map(([label, value]) => (
//             <View key={label} style={s.hwRow}>
//               <Text style={s.hwRowLabel}>{label}</Text>
//               <Text style={s.hwRowValue}>{value}</Text>
//             </View>
//           ))}

//           {result.recommended_facilities?.length > 0 && (
//             <View style={s.section}>
//               <Text style={s.sectionTitle}>Recommended Facilities</Text>
//               {result.recommended_facilities.slice(0, 5).map((f) => (
//                 <FacilityCard key={f.id} facility={f} />
//               ))}
//             </View>
//           )}
//         </>
//       )}
//     </View>
//   );
// }

// const s = StyleSheet.create({
//   container: { paddingBottom: 20 },

//   trustBanner: {
//     flexDirection: "row",
//     gap: 6,
//     backgroundColor: Colors.amberPale,
//     borderRadius: Radius.md,
//     padding: 10,
//     marginBottom: 12,
//     alignItems: "flex-start",
//   },
//   trustText: { fontFamily: Fonts.regular, fontSize: 12, color: Colors.brownLight, flex: 1, lineHeight: 18 },

//   statusBlock: {
//     borderWidth: 1.5,
//     borderRadius: Radius.lg,
//     padding: 16,
//     alignItems: "center",
//     marginBottom: 16,
//   },
//   statusIcon:     { fontSize: 32, marginBottom: 8 },
//   statusPill:     { paddingHorizontal: 12, paddingVertical: 4, borderRadius: Radius.full, marginBottom: 10 },
//   statusPillText: { fontFamily: Fonts.semibold, fontSize: 13, color: "#fff" },
//   parentMessage:  { fontFamily: Fonts.medium, fontSize: 14, color: Colors.earth, textAlign: "center", lineHeight: 22 },

//   gestNote: {
//     flexDirection: "row",
//     gap: 6,
//     marginTop: 10,
//     backgroundColor: Colors.amberPale,
//     borderRadius: Radius.md,
//     padding: 8,
//     alignItems: "flex-start",
//   },
//   gestNoteText: { fontFamily: Fonts.regular, fontSize: 12, color: Colors.amberDark, flex: 1, lineHeight: 18 },

//   section:      { marginBottom: 16 },
//   sectionTitle: { fontFamily: Fonts.semibold, fontSize: 14, color: Colors.earth, marginBottom: 10 },

//   stepRow: { flexDirection: "row", gap: 10, marginBottom: 8, alignItems: "flex-start" },
//   stepNum: { width: 22, height: 22, borderRadius: 11, alignItems: "center", justifyContent: "center" },
//   stepNumText: { fontFamily: Fonts.bold, fontSize: 11, color: "#fff" },
//   stepText: { fontFamily: Fonts.regular, fontSize: 13, color: Colors.brown, flex: 1, lineHeight: 20 },

//   noteRow: { flexDirection: "row", gap: 8, marginBottom: 6, alignItems: "flex-start" },
//   noteDot: { width: 5, height: 5, borderRadius: 3, backgroundColor: Colors.amber, marginTop: 7 },
//   noteText: { fontFamily: Fonts.regular, fontSize: 13, color: Colors.brown, flex: 1, lineHeight: 20 },

//   shareBtn: {
//     flexDirection: "row",
//     alignItems: "center",
//     justifyContent: "center",
//     gap: 6,
//     borderWidth: 1.5,
//     borderColor: Colors.coral,
//     borderRadius: Radius.lg,
//     padding: 12,
//     marginTop: 8,
//   },
//   shareBtnText: { fontFamily: Fonts.semibold, fontSize: 13, color: Colors.coral },

//   hwBanner: {
//     borderLeftWidth: 4,
//     paddingLeft: 12,
//     paddingVertical: 8,
//     marginBottom: 14,
//   },
//   hwLabel:    { fontFamily: Fonts.medium, fontSize: 11, color: Colors.brownLight, marginBottom: 2 },
//   hwDecision: { fontFamily: Fonts.bold, fontSize: 15 },
//   hwRow: {
//     backgroundColor: Colors.cream,
//     borderRadius: Radius.md,
//     padding: 10,
//     marginBottom: 6,
//   },
//   hwRowLabel: { fontFamily: Fonts.medium, fontSize: 11, color: Colors.brownLight, marginBottom: 2 },
//   hwRowValue: { fontFamily: Fonts.semibold, fontSize: 13, color: Colors.earth },
// });



// /**
//  * JaundiCare — ResultCard component
//  * Shows parent view by default.
//  * Health worker technical details only shown if role is health_worker.
//  */

// import React, { useMemo } from "react";
// import {
//   View, Text, TouchableOpacity,
//   StyleSheet, Share, LayoutAnimation, Platform, UIManager
// } from "react-native";
// import { Ionicons } from "@expo/vector-icons";
// import { Colors, Fonts, Radius, Shadow } from "../constants/colors";
// import { FacilityCard } from "./FacilityCard";
// import { decisionConfig } from "../constants/decisionMap";
// import { useAppStore } from "../store/appStore";
// import { useTranslations } from "../hooks/useTranslations";
// import { getNextStepTranslationKeys } from "../constants/screeningUtils";
// import type { ScreeningResult } from "../services/api";

// // Initialize Experimental LayoutAnimation cleanly for Android devices
// if (Platform.OS === "android" && UIManager.setLayoutAnimationEnabledExperimental) {
//   UIManager.setLayoutAnimationEnabledExperimental(true);
// }

// interface Props {
//   result: ScreeningResult;
//   babyName?: string;
//   gestationalAgeWeeks?: number;
// }

// function titleCase(str: string) {
//   return str.split("_").map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(" ");
// }

// export function ResultCard({ result, babyName, gestationalAgeWeeks }: Props) {
//   const { t } = useTranslations();
//   const role = useAppStore((s) => s.role);
//   const isHW = role === "health_worker";
//   const dm   = decisionConfig(result.final_decision);

//   // Retrieve matching internal translation identifier keys array
//   const stepKeys = useMemo(() => {
//     return getNextStepTranslationKeys(result.final_decision);
//   }, [result.final_decision]);

//   // Memoize recommended facilities segment to optimize performance
//   const displayFacilities = useMemo(() => {
//     if (!result.recommended_facilities) return [];
//     return result.recommended_facilities.slice(0, 5);
//   }, [result.recommended_facilities]);

//   // Apply fluid animation styling prior to context or state re-draw updates
//   React.useEffect(() => {
//     LayoutAnimation.configureNext(LayoutAnimation.Presets.easeInEaseOut);
//   }, [result]);

//   // Gestational age warning
//   let gestNote: string | null = null;
//   if (gestationalAgeWeeks != null) {
//     if (gestationalAgeWeeks < 35) {
//       gestNote = `Your baby was born at ${gestationalAgeWeeks} weeks — preterm babies have a lower threshold for jaundice treatment and need closer monitoring.`;
//     } else if (gestationalAgeWeeks < 38) {
//       gestNote = `Your baby was born at ${gestationalAgeWeeks} weeks (late preterm). Close monitoring is especially important in the first week.`;
//     }
//   }

//   // Confidence display
//   const raw = result.image_confidence;
//   const confidencePct = raw != null
//     ? (raw > 1 ? raw.toFixed(1) : (raw * 100).toFixed(1))
//     : "N/A";

//   const onShare = async () => {
//     const ageHours = result.baby_age_hours;
//     const ageDays  = ageHours != null ? Math.floor(ageHours / 24) : null;
//     const ageStr   = ageDays != null
//       ? ageDays > 0 ? `${ageDays} day(s) and ${ageHours! % 24} hour(s)` : `${ageHours} hours`
//       : "Unknown age";

//     const summary = `
// JaundiCare Screening Summary
// ─────────────────────────────
// Baby: ${babyName ?? "Baby"}
// Age at screening: ${ageStr}
// Date: ${new Date(result.created_at).toLocaleString()}

// RESULT: ${dm.label}

// Image analysis: ${titleCase(result.image_prediction ?? "N/A")} (${confidencePct}% confidence)
// Triage: ${result.raw_triage_level}
// Reason: ${result.final_decision_reason}

// NEXT STEPS:
// ${stepKeys.map((k, i) => `${i + 1}. ${t(k)}`).join("\n")}

// ─────────────────────────────
// This is a screening support tool only.
// It does not replace a doctor, midwife, or bilirubin test.
// Generated by JaundiCare
//     `.trim();

//     await Share.share({ message: summary, title: `JaundiCare — ${babyName ?? "Baby"} screening result` });
//   };

//   return (
//     <View style={s.container}>
//       {/* Trust banner */}
//       <View style={s.trustBanner}>
//         <Ionicons name="shield-checkmark-outline" size={14} color={Colors.brownLight} />
//         <Text style={s.trustText}>
//           {t("trust.title")} {t("trust.body")}
//         </Text>
//       </View>

//       {!isHW ? (
//         <>
//           {/* Status block */}
//           <View style={[s.statusBlock, { borderColor: dm.color, backgroundColor: dm.color + "12" }]}>
//             <Text style={s.statusIcon}>{dm.icon}</Text>
//             <View style={[s.statusPill, { backgroundColor: dm.color }]}>
//               <Text style={s.statusPillText}>{dm.label}</Text>
//             </View>
//             <Text style={s.parentMessage}>{result.parent_message}</Text>

//             {/* Gestational note */}
//             {gestNote && (
//               <View style={s.gestNote}>
//                 <Ionicons name="information-circle-outline" size={13} color={Colors.amberDark} />
//                 <Text style={s.gestNoteText}>{gestNote}</Text>
//               </View>
//             )}
//           </View>

//           {/* Next steps */}
//           <View style={s.section}>
//             <Text style={s.sectionTitle}>{t("result.what_next")}</Text>
//             {stepKeys.map((key, i) => (
//               <View key={key} style={s.stepRow}>
//                 <View style={[s.stepNum, { backgroundColor: dm.color }]}>
//                   <Text style={s.stepNumText}>{i + 1}</Text>
//                 </View>
//                 <Text style={s.stepText}>{t(key)}</Text>
//               </View>
//             ))}
//           </View>

//           {/* Facilities */}
//           {displayFacilities.length > 0 && (
//             <View style={s.section}>
//               <Text style={s.sectionTitle}>{t("result.facilities")}</Text>
//               {displayFacilities.map((f) => (
//                 <FacilityCard key={f.id} facility={f} />
//               ))}
//             </View>
//           )}

//           {/* Notes */}
//           {result.notes?.length > 0 && (
//             <View style={s.section}>
//               <Text style={s.sectionTitle}>{t("result.notes")}</Text>
//               {result.notes.map((note, i) => (
//                 <View key={i} style={s.noteRow}>
//                   <View style={s.noteDot} />
//                   <Text style={s.noteText}>{note}</Text>
//                 </View>
//               ))}
//             </View>
//           )}

//           {/* Share */}
//           <TouchableOpacity style={s.shareBtn} onPress={onShare}>
//             <Ionicons name="share-outline" size={16} color={Colors.coral} />
//             <Text style={s.shareBtnText}>Share screening summary</Text>
//           </TouchableOpacity>
//         </>
//       ) : (
//         <>
//           {/* Health worker view */}
//           <View style={[s.hwBanner, { borderLeftColor: dm.color }]}>
//             <Text style={s.hwLabel}>Final Decision</Text>
//             <Text style={[s.hwDecision, { color: dm.color }]}>{result.final_decision}</Text>
//           </View>

//           {[
//             ["Image Prediction",    titleCase(result.image_prediction ?? "N/A")],
//             ["Confidence",          `${confidencePct}%`],
//             ["Confidence Band",     result.confidence_band ?? "N/A"],
//             ["Baby Age",            result.baby_age_hours != null ? `${result.baby_age_hours} hours` : "N/A"],
//             ["Raw Triage Level",    result.raw_triage_level],
//             ["Raw Triage Reason",   result.raw_triage_reason],
//             ["Decision Reason",     result.final_decision_reason],
//           ].map(([label, value]) => (
//             <View key={label} style={s.hwRow}>
//               <Text style={s.hwRowLabel}>{label}</Text>
//               <Text style={s.hwRowValue}>{value}</Text>
//             </View>
//           ))}

//           {displayFacilities.length > 0 && (
//             <View style={s.section}>
//               <Text style={s.sectionTitle}>Recommended Facilities</Text>
//               {displayFacilities.map((f) => (
//                 <FacilityCard key={f.id} facility={f} />
//               ))}
//             </View>
//           )}
//         </>
//       )}
//     </View>
//   );
// }

// const s = StyleSheet.create({
//   container: { paddingBottom: 20 },

//   trustBanner: {
//     flexDirection: "row",
//     gap: 6,
//     backgroundColor: Colors.amberPale,
//     borderRadius: Radius.md,
//     padding: 10,
//     marginBottom: 12,
//     alignItems: "flex-start",
//   },
//   trustText: { fontFamily: Fonts.regular, fontSize: 12, color: Colors.brownLight, flex: 1, lineHeight: 18 },

//   statusBlock: {
//     borderWidth: 1.5,
//     borderRadius: Radius.lg,
//     padding: 16,
//     alignItems: "center",
//     marginBottom: 16,
//   },
//   statusIcon:     { fontSize: 32, marginBottom: 8 },
//   statusPill:     { paddingHorizontal: 12, paddingVertical: 4, borderRadius: Radius.full, marginBottom: 10 },
//   statusPillText: { fontFamily: Fonts.semibold, fontSize: 13, color: "#fff" },
//   parentMessage:  { fontFamily: Fonts.medium, fontSize: 14, color: Colors.earth, textAlign: "center", lineHeight: 22 },

//   gestNote: {
//     flexDirection: "row",
//     gap: 6,
//     marginTop: 10,
//     backgroundColor: Colors.amberPale,
//     borderRadius: Radius.md,
//     padding: 8,
//     alignItems: "flex-start",
//   },
//   gestNoteText: { fontFamily: Fonts.regular, fontSize: 12, color: Colors.amberDark, flex: 1, lineHeight: 18 },

//   section:      { marginBottom: 16 },
//   sectionTitle: { fontFamily: Fonts.semibold, fontSize: 14, color: Colors.earth, marginBottom: 10 },

//   stepRow: { flexDirection: "row", gap: 10, marginBottom: 8, alignItems: "flex-start" },
//   stepNum: { width: 22, height: 22, borderRadius: 11, alignItems: "center", justifyContent: "center" },
//   stepNumText: { fontFamily: Fonts.bold, fontSize: 11, color: "#fff" },
//   stepText: { fontFamily: Fonts.regular, fontSize: 13, color: Colors.brown, flex: 1, lineHeight: 20 },

//   noteRow: { flexDirection: "row", gap: 8, marginBottom: 6, alignItems: "flex-start" },
//   noteDot: { width: 5, height: 5, borderRadius: 3, backgroundColor: Colors.amber, marginTop: 7 },
//   noteText: { fontFamily: Fonts.regular, fontSize: 13, color: Colors.brown, flex: 1, lineHeight: 20 },

//   shareBtn: {
//     flexDirection: "row",
//     alignItems: "center",
//     justifyContent: "center",
//     gap: 6,
//     borderWidth: 1.5,
//     borderColor: Colors.coral,
//     borderRadius: Radius.lg,
//     padding: 12,
//     marginTop: 8,
//   },
//   shareBtnText: { fontFamily: Fonts.semibold, fontSize: 13, color: Colors.coral },

//   hwBanner: {
//     borderLeftWidth: 4,
//     paddingLeft: 12,
//     paddingVertical: 8,
//     marginBottom: 14,
//   },
//   hwLabel:    { fontFamily: Fonts.medium, fontSize: 11, color: Colors.brownLight, marginBottom: 2 },
//   hwDecision: { fontFamily: Fonts.bold, fontSize: 15 },
//   hwRow: {
//     backgroundColor: Colors.cream,
//     borderRadius: Radius.md,
//     padding: 10,
//     marginBottom: 6,
//   },
//   hwRowLabel: { fontFamily: Fonts.medium, fontSize: 11, color: Colors.brownLight, marginBottom: 2 },
//   hwRowValue: { fontFamily: Fonts.semibold, fontSize: 13, color: Colors.earth },
// });








/**
 * JaundiCare — ResultCard component
 * Shows parent view by default.
 * Health worker technical details only shown if role is health_worker.
 */

import React, { useMemo } from "react";
import {
  View, Text, TouchableOpacity,
  StyleSheet, Share, LayoutAnimation, Platform, UIManager
} from "react-native";
import { Ionicons } from "@expo/vector-icons";
import { Colors, Fonts, Radius, Shadow } from "../constants/colors";
import { FacilityCard } from "./FacilityCard";
import { decisionConfig } from "../constants/decisionMap";
import { useAppStore } from "../store/appStore";
import { useTranslations } from "../hooks/useTranslations";
import { getNextStepTranslationKeys } from "../constants/screeningUtils";
import type { ScreeningResult } from "../services/api";

if (Platform.OS === "android" && UIManager.setLayoutAnimationEnabledExperimental) {
  UIManager.setLayoutAnimationEnabledExperimental(true);
}

interface Props {
  result: ScreeningResult;
  babyName?: string;
  gestationalAgeWeeks?: number;
}

function titleCase(str: string) {
  return str.split("_").map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(" ");
}

export function ResultCard({ result, babyName, gestationalAgeWeeks }: Props) {
  const { t } = useTranslations();
  const role = useAppStore((s) => s.role);
  const isHW = role === "health_worker";
  const dm   = decisionConfig(result.final_decision);

  const stepKeys = useMemo(() => {
    return getNextStepTranslationKeys(result.final_decision);
  }, [result.final_decision]);

  const displayFacilities = useMemo(() => {
    if (!result.recommended_facilities) return [];
    return result.recommended_facilities.slice(0, 5);
  }, [result.recommended_facilities]);

  // Protected animation pipeline layer
  React.useEffect(() => {
    try {
      LayoutAnimation.configureNext(LayoutAnimation.Presets.easeInEaseOut);
    } catch (e) {
      console.warn("[ResultCard] LayoutAnimation caught an interface mutation anomaly:", e);
    }
  }, [result.created_at, isHW]); // Fixed: Swapped missing result.id for deterministic result.created_at timestamp

  // Gestational age calculation
  const gestNote = useMemo(() => {
    if (gestationalAgeWeeks == null) return null;
    if (gestationalAgeWeeks < 35) {
      return `Your baby was born at ${gestationalAgeWeeks} weeks — preterm babies have a lower threshold for jaundice treatment and need closer monitoring.`;
    }
    if (gestationalAgeWeeks < 38) {
      return `Your baby was born at ${gestationalAgeWeeks} weeks (late preterm). Close monitoring is especially important in the first week.`;
    }
    return null;
  }, [gestationalAgeWeeks]);

  const confidencePct = useMemo(() => {
    const raw = result.image_confidence;
    if (raw == null) return "N/A";
    return raw > 1 ? raw.toFixed(1) : (raw * 100).toFixed(1);
  }, [result.image_confidence]);

  const onShare = async () => {
    const ageHours = result.baby_age_hours;
    const ageDays  = ageHours != null ? Math.floor(ageHours / 24) : null;
    const ageStr   = ageDays != null
      ? ageDays > 0 ? `${ageDays} day(s) and ${ageHours! % 24} hour(s)` : `${ageHours} hours`
      : "Unknown age";

    // Standardized date format parsing to replace cross-platform .toLocaleString discrepancies
    const formattedDate = result.created_at 
      ? new Date(result.created_at).toISOString().split("T")[0] 
      : "N/A";

    const summary = `
JaundiCare Screening Summary
─────────────────────────────
Baby: ${babyName ?? "Baby"}
Age at screening: ${ageStr}
Date: ${formattedDate}

RESULT: ${dm.label}

Image analysis: ${titleCase(result.image_prediction ?? "N/A")} (${confidencePct}% confidence)
Triage: ${result.raw_triage_level}
Reason: ${result.final_decision_reason}

NEXT STEPS:
${stepKeys.map((k, i) => `${i + 1}. ${t(k)}`).join("\n")}

─────────────────────────────
This is a screening support tool only.
It does not replace a doctor, midwife, or bilirubin test.
Generated by JaundiCare
    `.trim();

    try {
      await Share.share({ 
        message: summary, 
        title: `JaundiCare — ${babyName ?? "Baby"} screening result` 
      });
    } catch (err) {
      console.error("[ResultCard] Sharing protocol system allocation failure:", err);
    }
  };

  return (
    <View style={s.container}>
      <View style={s.trustBanner}>
        <Ionicons name="shield-checkmark-outline" size={14} color={Colors.brownLight} style={s.iconSpacer} />
        <Text style={s.trustText}>
          {t("trust.title")} {t("trust.body")}
        </Text>
      </View>

      {!isHW ? (
        <>
          <View style={[s.statusBlock, { borderColor: dm.color, backgroundColor: dm.color + "12" }]}>
            <Text style={s.statusIcon}>{dm.icon}</Text>
            <View style={[s.statusPill, { backgroundColor: dm.color }]}>
              <Text style={s.statusPillText}>{dm.label}</Text>
            </View>
            <Text style={s.parentMessage}>{result.parent_message}</Text>

            {gestNote && (
              <View style={s.gestNote}>
                <Ionicons name="information-circle-outline" size={13} color={Colors.amberDark} style={s.iconSpacer} />
                <Text style={s.gestNoteText}>{gestNote}</Text>
              </View>
            )}
          </View>

          <View style={s.section}>
            <Text style={s.sectionTitle}>{t("result.what_next")}</Text>
            {stepKeys.map((key, i) => (
              <View key={`step-${key}`} style={s.stepRow}>
                <View style={[s.stepNum, { backgroundColor: dm.color }]}>
                  <Text style={s.stepNumText}>{i + 1}</Text>
                </View>
                <Text style={s.stepText}>{t(key)}</Text>
              </View>
            ))}
          </View>

          {displayFacilities.length > 0 && (
            <View style={s.section}>
              <Text style={s.sectionTitle}>{t("result.facilities")}</Text>
              {displayFacilities.map((f) => (
                <FacilityCard key={`fac-${f.id}`} facility={f} />
              ))}
            </View>
          )}

          {result.notes && result.notes.length > 0 && (
            <View style={s.section}>
              <Text style={s.sectionTitle}>{t("result.notes")}</Text>
              {result.notes.map((note, i) => (
                <View key={`note-${i}-${note.slice(0, 10)}`} style={s.noteRow}>
                  <View style={s.noteDot} />
                  <Text style={s.noteText}>{note}</Text>
                </View>
              ))}
            </View>
          )}

          <TouchableOpacity style={s.shareBtn} onPress={onShare} activeOpacity={0.8}>
            <Ionicons name="share-outline" size={16} color={Colors.coral} />
            <Text style={s.shareBtnText}>Share screening summary</Text>
          </TouchableOpacity>
        </>
      ) : (
        <>
          <View style={[s.hwBanner, { borderLeftColor: dm.color }]}>
            <Text style={s.hwLabel}>Final Decision</Text>
            <Text style={[s.hwDecision, { color: dm.color }]}>{result.final_decision}</Text>
          </View>

          {[
            ["Image Prediction",    titleCase(result.image_prediction ?? "N/A")],
            ["Confidence",          `${confidencePct}%`],
            ["Confidence Band",     result.confidence_band ?? "N/A"],
            ["Baby Age",            result.baby_age_hours != null ? `${result.baby_age_hours} hours` : "N/A"],
            ["Raw Triage Level",    result.raw_triage_level],
            ["Raw Triage Reason",   result.raw_triage_reason],
            ["Decision Reason",     result.final_decision_reason],
          ].map(([label, value]) => (
            <View key={`hw-row-${label}`} style={s.hwRow}>
              <Text style={s.hwRowLabel}>{label}</Text>
              <Text style={s.hwRowValue}>{value}</Text>
            </View>
          ))}

          {displayFacilities.length > 0 && (
            <View style={s.section}>
              <Text style={s.sectionTitle}>Recommended Facilities</Text>
              {displayFacilities.map((f) => (
                <FacilityCard key={`hw-fac-${f.id}`} facility={f} />
              ))}
            </View>
          )}
        </>
      )}
    </View>
  );
}

const s = StyleSheet.create({
  container: { paddingBottom: 20 },
  trustBanner: {
    flexDirection: "row",
    backgroundColor: Colors.amberPale,
    borderRadius: Radius.md,
    padding: 10,
    marginBottom: 12,
    alignItems: "flex-start",
  },
  iconSpacer: { marginRight: 6, marginTop: 1 },
  trustText: { fontFamily: Fonts.regular, fontSize: 12, color: Colors.brownLight, flex: 1, lineHeight: 18 },
  statusBlock: {
    borderWidth: 1.5,
    borderRadius: Radius.lg,
    padding: 16,
    alignItems: "center",
    marginBottom: 16,
  },
  statusIcon:     { fontSize: 32, marginBottom: 8 },
  statusPill:     { paddingHorizontal: 12, paddingVertical: 4, borderRadius: Radius.full, marginBottom: 10 },
  statusPillText: { fontFamily: Fonts.semibold, fontSize: 13, color: "#fff" },
  parentMessage:  { fontFamily: Fonts.medium, fontSize: 14, color: Colors.earth, textAlign: "center", lineHeight: 22 },
  gestNote: {
    flexDirection: "row",
    marginTop: 10,
    backgroundColor: Colors.amberPale,
    borderRadius: Radius.md,
    padding: 8,
    alignItems: "flex-start",
  },
  gestNoteText: { fontFamily: Fonts.regular, fontSize: 12, color: Colors.amberDark, flex: 1, lineHeight: 18 },
  section:      { marginBottom: 16 },
  sectionTitle: { fontFamily: Fonts.semibold, fontSize: 14, color: Colors.earth, marginBottom: 10 },
  stepRow: { flexDirection: "row", gap: 10, marginBottom: 8, alignItems: "flex-start" },
  stepNum: { width: 22, height: 22, borderRadius: 11, alignItems: "center", justifyContent: "center" },
  stepNumText: { fontFamily: Fonts.bold, fontSize: 11, color: "#fff" },
  stepText: { fontFamily: Fonts.regular, fontSize: 13, color: Colors.brown, flex: 1, lineHeight: 20 },
  noteRow: { flexDirection: "row", gap: 8, marginBottom: 6, alignItems: "flex-start" },
  noteDot: { width: 5, height: 5, borderRadius: 3, backgroundColor: Colors.amber, marginTop: 7 },
  noteText: { fontFamily: Fonts.regular, fontSize: 13, color: Colors.brown, flex: 1, lineHeight: 20 },
  shareBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    borderWidth: 1.5,
    borderColor: Colors.coral,
    borderRadius: Radius.lg,
    padding: 12,
    marginTop: 8,
  },
  shareBtnText: { fontFamily: Fonts.semibold, fontSize: 13, color: Colors.coral },
  hwBanner: {
    borderLeftWidth: 4,
    paddingLeft: 12,
    paddingVertical: 8,
    marginBottom: 14,
  },
  hwLabel:    { fontFamily: Fonts.medium, fontSize: 11, color: Colors.brownLight, marginBottom: 2 },
  hwDecision: { fontFamily: Fonts.bold, fontSize: 15 },
  hwRow: {
    backgroundColor: Colors.cream,
    borderRadius: Radius.md,
    padding: 10,
    marginBottom: 6,
  },
  hwRowLabel: { fontFamily: Fonts.medium, fontSize: 11, color: Colors.brownLight, marginBottom: 2 },
  hwRowValue: { fontFamily: Fonts.semibold, fontSize: 13, color: Colors.earth },
});